services:
  oracle-database-express:
    container_name: oracle_database_express
    image: container-registry.oracle.com/database/express:latest
    env_file:
     - ./.env
    
    volumes:
      - ./data:/opt/oracle/ordata:rw
    
    hostname: oracledbhost
    restart: always
    init: true
    tty: true
    ports: 
      - 1521:1521
      - 5500:5500